version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: pay-gateway-postgres
    environment:
      POSTGRES_DB: billing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pay-gateway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: pay-gateway-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pay-gateway-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 支付网关应用
  pay-gateway:
    build: .
    container_name: pay-gateway-app
    environment:
      # 服务器配置
      SERVER_PORT: 8080
      SERVER_MODE: release
      SERVER_READ_TIMEOUT: 15s
      SERVER_WRITE_TIMEOUT: 15s
      
      # 数据库配置
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: billing
      DB_SSLMODE: disable
      DB_MAX_IDLE_CONNS: 10
      DB_MAX_OPEN_CONNS: 100
      
      # Redis配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      REDIS_POOL_SIZE: 10
      REDIS_MIN_IDLE_CONNS: 5
      
      # Google Play配置
      GOOGLE_SERVICE_ACCOUNT_FILE: /app/config/service-account.json
      GOOGLE_PACKAGE_NAME: com.example.app
      GOOGLE_WEBHOOK_SECRET: your-webhook-secret
      
      # JWT配置
      JWT_SECRET: your-jwt-secret-key
      JWT_EXPIRE_TIME: 24h
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pay-gateway-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: pay-gateway-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - pay-gateway
    networks:
      - pay-gateway-network

volumes:
  postgres_data:
  redis_data:

networks:
  pay-gateway-network:
    driver: bridge
